In [1]:
from numpy.polynomial.hermite import hermint
hermint([1,2,3]) # integrate once, value 0 at 0.

array([1. , 0.5, 0.5, 0.5])

In [2]:
hermint([1,2,3], m=2) # integrate twice, value & deriv 0 at 0

array([-0.5       ,  0.5       ,  0.125     ,  0.08333333,  0.0625    ])

In [3]:
hermint([1,2,3], k=1) # integrate once, value 1 at 0.

array([2. , 0.5, 0.5, 0.5])

In [4]:
hermint([1,2,3], lbnd=-1) # integrate once, value 0 at -1

array([-2. ,  0.5,  0.5,  0.5])

In [5]:
hermint([1,2,3], m=2, k=[1,2], lbnd=-1)

array([ 1.66666667, -0.5       ,  0.125     ,  0.08333333,  0.0625    ])