In [1]:
import numpy as np 

In [46]:
ar1  = np.array([[3,4,5],[5,6,7]])
ar2 = np.array([ [4,5,6],[7,8,9]])

In [5]:
np.add(ar1,ar2)

array([[ 7,  9, 11],
       [12, 14, 16]])

In [12]:
def add(X,Y):
    for i in range(len(X)):
        
        # iterate through columns
        for j in range(len(X[0])):
            result[i][j] = X[i][j] + Y[i][j]
 
    for r in result:
        return r 

In [13]:
add(ar1,ar2)

NameError: name 'result' is not defined

In [19]:
def add(X,Y):
    
    result = [map(sum, zip(*t)) for t in zip(X, Y)]
    return print(result)

In [20]:
add(ar1,ar2)

[<map object at 0x0000022C98D2E6A0>, <map object at 0x0000022C98D2E8B0>]


In [ ]:
bbbbbbbbbbbbbbbbbbbbbbbbbbbbb

In [21]:
import numpy as np 

In [22]:
ar = np.array([[1,2,3],[4,5,6]])

In [23]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
def transpose(mat):
    return map(list,zip(*mat))

In [44]:
transpose(ar)

In [49]:
import sys
def matrix_multiply(A,B):
    rowsA = len(A)
    colsA = len(A[0])

    rowsB = len(B)
    colsB = len(B[0])

    if colsA != rowsB:
        print('Number of A columns must equal number of B rows.')
        sys.exit()

    C = zeros_matrix(rowsA, colsB)

    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total


In [50]:
np.multiply(ar1,ar2)

array([[12, 20, 30],
       [35, 48, 63]])

In [52]:
ar1,ar2

(array([[3, 4, 5],
        [5, 6, 7]]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [51]:
matrix_multiply(ar1,ar2)

Number of A columns must equal number of B rows.


SystemExit: 

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [64]:
def zeros(rows, cols):
    A = []
    for i in range(rows):
        A.append([])
        for j in range(cols):
            A[-1].append(0.0)

In [65]:
zeros(2,3)

In [66]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [67]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])