### Return multidimensional Discrete Cosine Transform along the specified axes.

In [2]:
import numpy as np

In [7]:
from scipy.fft import dctn, idctn
rng = np.random.default_rng()
y = rng.standard_normal((16, 16))
np.allclose(y, idctn(dctn(y)))

True

In [8]:
y

array([[-1.41325448e+00, -8.34028657e-01, -6.38698069e-01,
        -2.38626058e-01, -5.10386211e-01, -7.27808572e-02,
         1.78655025e+00, -3.99168978e-01,  1.42359829e+00,
        -1.00403016e+00, -2.13080789e-01, -1.47761588e+00,
        -1.13689914e+00, -1.10094699e+00,  2.54311706e-01,
         3.70479487e-01],
       [-4.84351591e-01, -9.35190352e-01,  5.90322109e-01,
         1.25229906e+00, -1.15132845e+00, -1.80199031e-01,
        -1.83082068e+00,  5.91618918e-01, -3.10823971e-01,
         2.47679926e-01, -5.29418682e-01, -6.31968718e-01,
        -2.30628231e-01, -1.80819180e-01,  9.03116352e-01,
         2.21275253e+00],
       [ 1.28136053e+00,  1.35605182e+00,  4.13754168e-02,
        -1.89904428e+00,  1.36960414e-01, -2.87876554e-03,
        -1.31851460e+00,  1.41378571e-01,  1.14852190e-01,
         1.83534388e-01,  7.47091354e-01,  1.21785130e-01,
        -8.19995239e-01,  2.22329493e+00,  8.15601391e-02,
         8.91342367e-01],
       [ 9.43034125e-01,  1.98746825e

In [9]:
from numpy import empty,arange,exp,real,imag,pi
from numpy.fft import rfft,irfft

In [12]:
def dct(y):
    N = len(y)
    y2 = empty(2*N,float)
    y2[:N] = y[:]
    y2[N:] = y[::-1]

    c = rfft(y2)
    phi = exp(-1j*pi*arange(N)/(2*N))
    return real(phi*c[:N])

def dct2(y):
    M = y.shape[0]
    N = y.shape[1]
    a = empty([M,N],float)
    b = empty([M,N],float)

    for i in range(M):
        a[i,:] = dct(y[i,:])
    for j in range(N):
        b[:,j] = dct(a[:,j])

    return b


In [13]:
dct2(y)

array([[-4.71364462e+01, -1.01115050e+02,  8.17364889e+01,
        -6.06271960e+00,  1.27564128e+01, -3.10165170e+01,
         7.98211854e+01, -1.02597600e+01, -1.68442484e+01,
        -3.75816113e+01, -4.02391402e+01,  3.26819980e+00,
        -4.88043748e+01, -2.53962017e+01, -4.14200485e+01,
        -1.50048052e+01],
       [-1.93271849e+00, -1.65537933e+01, -1.32512513e+01,
        -1.07216483e+01,  3.30884366e+01, -5.09438154e+01,
        -5.20436235e+01, -1.69740522e+00, -4.85432309e+01,
        -3.22219444e+01,  1.67368083e+01, -1.82643479e+01,
         8.62753119e+01, -5.67999022e+01, -2.68137360e+01,
         4.99694364e+00],
       [-2.44278877e+01, -5.70552319e+00,  4.13360662e+01,
        -1.14117319e+01,  3.83358398e+01, -6.78656075e+00,
        -2.73270499e+01,  4.31146230e+01,  5.30169132e+01,
         1.30674374e+01,  5.19450957e+00, -6.97705050e+00,
         2.16734921e+01,  1.59875885e+01,  2.06320293e+01,
         1.62907409e+01],
       [-4.24373798e+01,  2.67826904e

In [14]:
dctn(y)

array([[-4.71364462e+01, -1.01115050e+02,  8.17364889e+01,
        -6.06271960e+00,  1.27564128e+01, -3.10165170e+01,
         7.98211854e+01, -1.02597600e+01, -1.68442484e+01,
        -3.75816113e+01, -4.02391402e+01,  3.26819980e+00,
        -4.88043748e+01, -2.53962017e+01, -4.14200485e+01,
        -1.50048052e+01],
       [-1.93271849e+00, -1.65537933e+01, -1.32512513e+01,
        -1.07216483e+01,  3.30884366e+01, -5.09438154e+01,
        -5.20436235e+01, -1.69740522e+00, -4.85432309e+01,
        -3.22219444e+01,  1.67368083e+01, -1.82643479e+01,
         8.62753119e+01, -5.67999022e+01, -2.68137360e+01,
         4.99694364e+00],
       [-2.44278877e+01, -5.70552319e+00,  4.13360662e+01,
        -1.14117319e+01,  3.83358398e+01, -6.78656075e+00,
        -2.73270499e+01,  4.31146230e+01,  5.30169132e+01,
         1.30674374e+01,  5.19450957e+00, -6.97705050e+00,
         2.16734921e+01,  1.59875885e+01,  2.06320293e+01,
         1.62907409e+01],
       [-4.24373798e+01,  2.67826904e