### Shift the zero-frequency component to the center of the spectrum.

In [1]:
import numpy as np

In [2]:
freqs = np.fft.fftfreq(10, 0.1)
freqs

array([ 0.,  1.,  2.,  3.,  4., -5., -4., -3., -2., -1.])

In [3]:
np.fft.fftshift(freqs)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [4]:
freqs = np.fft.fftfreq(9, d=1./9).reshape(3, 3)
freqs

array([[ 0.,  1.,  2.],
       [ 3.,  4., -4.],
       [-3., -2., -1.]])

In [5]:
np.fft.fftshift(freqs, axes=(1,))

array([[ 2.,  0.,  1.],
       [-4.,  3.,  4.],
       [-1., -3., -2.]])