In [1]:
from __future__ import annotations


def geometric_series(
    nth_term: float | int,
    start_term_a: float | int,
    common_ratio_r: float | int,
) -> list[float | int]:
    """
    Pure Python implementation of Geometric Series algorithm
    :param nth_term: The last term (nth term of Geometric Series)
    :param start_term_a : The first term of Geometric Series
    :param common_ratio_r : The common ratio between all the terms
    :return: The Geometric Series starting from first term a and multiple of common
        ration with first term with increase in power till last term (nth term)
    Examples:
    >>> geometric_series(4, 2, 2)
    [2, 4.0, 8.0, 16.0]
    >>> geometric_series(4.0, 2.0, 2.0)
    [2.0, 4.0, 8.0, 16.0]
    >>> geometric_series(4.1, 2.1, 2.1)
    [2.1, 4.41, 9.261000000000001, 19.448100000000004]
    >>> geometric_series(4, 2, -2)
    [2, -4.0, 8.0, -16.0]
    >>> geometric_series(4, -2, 2)
    [-2, -4.0, -8.0, -16.0]
    >>> geometric_series(-4, 2, 2)
    []
    >>> geometric_series(0, 100, 500)
    []
    >>> geometric_series(1, 1, 1)
    [1]
    >>> geometric_series(0, 0, 0)
    []
    """
    if not all((nth_term, start_term_a, common_ratio_r)):
        return []
    series: list[float | int] = []
    power = 1
    multiple = common_ratio_r
    for _ in range(int(nth_term)):
        if not series:
            series.append(start_term_a)
        else:
            power += 1
            series.append(float(start_term_a * multiple))
            multiple = pow(float(common_ratio_r), power)
    return series

In [2]:
import mpmath as mp

In [6]:
mp.hyper([2,3],[4,5],0.15)

mpf('1.0463828000626856')

In [1]:
abs(-1)

1

In [1]:
import numpy as np

In [23]:
a = np.array([[3,4,5],[5,6,7]])

In [3]:
a.size

6

In [6]:
a.shape

(2, 3)

In [29]:
def shape(A):
    return (len(A), len(A[0]))

In [7]:
a = size(a)

5

In [12]:
def identity(n):
    return [[(1 if i==j else 0) for j in range(n)] for i in range(n)]

In [21]:
def colconcat(A, B):
    return A + B

In [22]:
b = np.array([[4,5,6],[6,7,8]])

In [24]:
colconcat(a,b)

array([[ 7,  9, 11],
       [11, 13, 15]])

In [25]:
a,b

(array([[3, 4, 5],
        [5, 6, 7]]),
 array([[4, 5, 6],
        [6, 7, 8]]))

In [26]:
def transpose(A):
    
    (r, c) = size(A)
    return [[A[i][j] for i in range(r)] for j in range(c)]

In [27]:
transpose(a)

[[3, 5], [4, 6], [5, 7]]

In [28]:
a.T

array([[3, 5],
       [4, 6],
       [5, 7]])