https://doc.sagemath.org/html/en/reference/functions/sage/functions/bessel.html#sage.functions.bessel.Function_Bessel_Y

In [1]:
import scipy.special as sp

In [4]:
sp.jnjnp_zeros(3)

(array([0.        , 1.84118378, 2.40482556]),
 array([0, 1, 0], dtype=int32),
 array([0, 1, 1], dtype=int32),
 array([1, 1, 0], dtype=int32))

In [5]:
import mpmath

mpf('6.3801618959239832')