In [1]:
import scipy.special as sp

In [2]:
sp.jnjnp_zeros(2)

(array([0.        , 1.84118378]),
 array([0, 1], dtype=int32),
 array([0, 1], dtype=int32),
 array([1, 1], dtype=int32))

In [4]:
sp.jnyn_zeros(2,3)

(array([ 5.1356223 ,  8.41724414, 11.61984117]),
 array([3.05423693, 6.70613319, 9.96946782]),
 array([ 3.38424177,  6.79380751, 10.02347798]),
 array([ 5.00258293,  8.3507247 , 11.57419547]))

In [6]:
sp.jn_zeros(2,3)

array([ 5.1356223 ,  8.41724414, 11.61984117])

In [7]:
sp.jnp_zeros(2,3)

array([3.05423693, 6.70613319, 9.96946782])

In [8]:
sp.yn_zeros(2,3)

array([ 3.38424177,  6.79380751, 10.02347798])

In [9]:
sp.ynp_zeros(2,3)

array([ 5.00258293,  8.3507247 , 11.57419547])

In [10]:
sp.y0_zeros(2,3)

(array([-2.40301663+0.53988231j, -5.5198767 +0.54718001j]),
 array([ 0.10074769-0.88196771j, -0.02924642+0.5871695j ]))

In [11]:
sp.y1_zeros(2,3)

(array([-0.50274327+0.78624371j, -3.83353519+0.56235654j]),
 array([-0.45952768+1.31710194j,  0.04830191-0.69251288j]))

In [12]:
sp.y1p_zeros(2,3)

(array([ 0.57678513+0.90398479j, -1.94047734+0.72118592j]),
 array([-0.76349709+0.58924486j,  0.16206401-0.95202789j]))