In [1]:
# Python3 program to decompose
# a matrix using Cholesky
# Decomposition
import math
MAX = 100;

def Cholesky_Decomposition(matrix, n):

	lower = [[0 for x in range(n + 1)]
				for y in range(n + 1)];

	# Decomposing a matrix
	# into Lower Triangular
	for i in range(n):
		for j in range(i + 1):
			sum1 = 0;

			# summation for diagonals
			if (j == i):
				for k in range(j):
					sum1 += pow(lower[j][k], 2);
				lower[j][j] = int(math.sqrt(matrix[j][j] - sum1));
			else:
				
				# Evaluating L(i, j)
				# using L(j, j)
				for k in range(j):
					sum1 += (lower[i][k] *lower[j][k]);
				if(lower[j][j] > 0):
					lower[i][j] = int((matrix[i][j] - sum1) /
											lower[j][j]);

	# Displaying Lower Triangular
	# and its Transpose
	print("Lower Triangular\t\tTranspose");
	for i in range(n):
		
		# Lower Triangular
		for j in range(n):
			print(lower[i][j], end = "\t");
		print("", end = "\t");
		
		# Transpose of
		# Lower Triangular
		for j in range(n):
			print(lower[j][i], end = "\t");
		print("");

# Driver Code
n = 3;
matrix = [[4, 12, -16],
		[12, 37, -43],
		[-16, -43, 98]];
Cholesky_Decomposition(matrix, n);

# This code is contributed by mits


Lower Triangular		Transpose
2	0	0		2	6	-8	
6	1	0		0	1	5	
-8	5	3		0	0	3	


In [3]:
from scipy.linalg import cholesky
import numpy as np
a = np.array([[1,-2j],[2j,5]])
L = cholesky(a, lower=True)
L

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [4]:
L @ L.T.conj()


array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [5]:
L = cholesky(matrix)

In [6]:
L

array([[ 2.,  6., -8.],
       [ 0.,  1.,  5.],
       [ 0.,  0.,  3.]])