### Efficient Toeplitz Matrix-Matrix Multiplication using FFT

In [1]:
import numpy as np 

In [2]:
c = np.array([1, 3, 6, 10])    # First column of T
r = np.array([1, -1, -2, -3])  # First row of T
x = np.array([[1, 10], [2, 11], [2, 11], [5, 19]])

In [3]:
from scipy.linalg import toeplitz, matmul_toeplitz
matmul_toeplitz((c, r), x)

array([[-20., -80.],
       [ -7.,  -8.],
       [  9.,  85.],
       [ 33., 218.]])

In [4]:
toeplitz(c, r) @ x

array([[-20, -80],
       [ -7,  -8],
       [  9,  85],
       [ 33, 218]])

In [5]:
n = 1000000
matmul_toeplitz([1] + [0]*(n-1), np.ones(n))

array([1., 1., 1., ..., 1., 1., 1.])