### Solves the linear equation set a * x = b for the unknown x for square a matrix. 

In [3]:
import numpy as np
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
from scipy import linalg
x = linalg.solve(a, b)
x

array([ 2., -2.,  9.])

In [4]:
np.dot(a, x) == b

array([ True,  True,  True])

In [11]:
def solve(a,b):
    import numpy.linalg as ln 
    x = ln.inv(a).dot(b)
    return np.array(x)

In [12]:
solve(a,b)

array([ 2., -2.,  9.])

In [13]:
np.dot(a, x) == b

array([ True,  True,  True])

In [ ]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

In [ ]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)

In [ ]:
np.linalg.inv(A).dot(y)

In [ ]:
from numpy.linalg import *

def solve(a,b):
    from numpy.linalg import inv, dot
    x = inv(a).dot(b)
    return np.array(x)

In [ ]:
solve(A,y)

In [ ]:
from numpy.linalg import inv, dot

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.05-Solve-Systems-of-Linear-Equations-in-Python.html

In [ ]:
import functools
import operator
import warnings

In [ ]:
def _solve_dispatcher(a, b):
    return (a, b)

In [ ]:
array_function_dispatch = functools.partial(
    overrides.array_function_dispatch, module='numpy.linalg')

In [ ]:
@array_function_dispatch(_solve_dispatcher)
def solve(a, b):
    """
    Solve a linear matrix equation, or system of linear scalar equations.
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.
    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.
    Raises
    ------
    LinAlgError
        If `a` is singular or not square.
    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.
    Notes
    -----
    .. versionadded:: 1.8.0
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    The solutions are computed using LAPACK routine ``_gesv``.
    `a` must be square and of full-rank, i.e., all rows (or, equivalently,
    columns) must be linearly independent; if either is not true, use
    `lstsq` for the least-squares best "solution" of the
    system/equation.
    References
    ----------
    .. [1] G. Strang, *Linear Algebra and Its Applications*, 2nd Ed., Orlando,
           FL, Academic Press, Inc., 1980, pg. 22.
    Examples
    --------
    Solve the system of equations ``x0 + 2 * x1 = 1`` and ``3 * x0 + 5 * x1 = 2``:
    >>> a = np.array([[1, 2], [3, 5]])
    >>> b = np.array([1, 2])
    >>> x = np.linalg.solve(a, b)
    >>> x
    array([-1.,  1.])
    Check that the solution is correct:
    >>> np.allclose(np.dot(a, x), b)
    True
    """
    a, _ = _makearray(a)
    _assert_stacked_2d(a)
    _assert_stacked_square(a)
    b, wrap = _makearray(b)
    t, result_t = _commonType(a, b)

    # We use the b = (..., M,) logic, only if the number of extra dimensions
    # match exactly
    if b.ndim == a.ndim - 1:
        gufunc = _umath_linalg.solve1
    else:
        gufunc = _umath_linalg.solve

    signature = 'DD->D' if isComplexType(t) else 'dd->d'
    extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
    r = gufunc(a, b, signature=signature, extobj=extobj)

    return wrap(r.astype(result_t, copy=False))

In [ ]:
np.dot(A,y)

In [ ]:
A,y

In [16]:
sum([1,2,3])

6

In [17]:
def sum(*args):
    result = 0
    for value in args:
        result +=value
    return result

In [18]:
sum(1,2,3)

6

In [20]:
sum([1,2,3])

TypeError: unsupported operand type(s) for +=: 'int' and 'list'