### Compute the subspace angles between two matrices.

In [1]:
from numpy.random import default_rng
from scipy.linalg import hadamard, subspace_angles
rng = default_rng()
H = hadamard(4)
print(H)

[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]


In [2]:
import numpy as np 

In [3]:
np.rad2deg(subspace_angles(H[:, :2], H[:, 2:]))

array([90., 90.])

In [4]:
subspace_angles(H[:, :2], H[:, :2]) <= 2 * np.finfo(float).eps

array([ True,  True])

In [5]:
x = rng.standard_normal((4, 3))
np.rad2deg(subspace_angles(x[:, :2], x[:, [2]]))

array([46.53883656])