In [ ]:
import Decompositions as dcom

In [1]:
import numpy as np
from scipy.linalg import lu
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
p, l, u = lu(A)
np.allclose(A - p @ l @ u, np.zeros((4, 4)))

True

In [ ]:
p,l,u

In [ ]:
l,u= dcom.lu(A)


In [ ]:
l,u

In [ ]:
def lu(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

In [ ]:
l,u = lu(A)

In [ ]:
import numpy as np

# LU decomposition of square systems
def Gaussian_Elimination(A):
    m=A.shape[0]
    n=A.shape[1]
    if(m!=n):
        print ('Matrix is not square!')
        return
    for k in range(0,n-1):
        if A[k,k] == 0:
            return
        for i in range(k+1,n):
            A[i,k]=A[i,k]/A[k,k]
        for j in range(k+1,n):
            for i in range(k+1,n):
                A[i,j]-=A[i,k]*A[k,j]

In [ ]:
print(Gaussian_Elimination(A))

In [ ]:
def LU(A):
	
	n = len(A) # Give us total of lines

	# (1) Extract the b vector
	b = [0 for i in range(n)]
	for i in range(0,n):
		b[i]=A[i][n]

	# (2) Fill L matrix and its diagonal with 1
	L = [[0 for i in range(n)] for i in range(n)]
	for i in range(0,n):
		L[i][i] = 1

	# (3) Fill U matrix
	U = [[0 for i in range(0,n)] for i in range(n)]
	for i in range(0,n):
		for j in range(0,n):
			U[i][j] = A[i][j]

	n = len(U)

	# (4) Find both U and L matrices
	for i in range(0,n): # for i in [0,1,2,..,n]
		# (4.1) Find the maximun value in a column in order to change lines
		maxElem = abs(U[i][i])
		maxRow = i
		for k in range(i+1, n): # Interacting over the next line
			if(abs(U[k][i]) > maxElem):
				maxElem = abs(U[k][i]) # Next line on the diagonal
				maxRow = k

		# (4.2) Swap the rows pivoting the maxRow, i is the current row
		for k in range(i, n): # Interacting column by column
			tmp=U[maxRow][k]
			U[maxRow][k]=U[i][k]
			U[i][k]=tmp

		# (4.3) Subtract lines
		for k in range(i+1,n):
			c = -U[k][i]/float(U[i][i])
			L[k][i] = c # (4.4) Store the multiplier
			for j in range(i, n):
				U[k][j] += c*U[i][j] # Multiply with the pivot line and subtract

		# (4.5) Make the rows bellow this one zero in the current column
		for k in range(i+1, n):
			U[k][i]=0

	n = len(L)

	# (5) Perform substitutioan Ly=b
	y = [0 for i in range(n)]
	for i in range(0,n,1):
		y[i] = b[i]/float(L[i][i])
		for k in range(0,i,1):
			y[i] -= y[k]*L[i][k]

	n = len(U)

	# (6) Perform substitution Ux=y
	x = [0 in range(n)]
	for i in range(n-1,-1,-1):
		x[i] = y[i]/float(U[i][i])
		for k in range (i-1,-1,-1):
			U[i] -= x[i]*U[i][k]

	return x

In [ ]:
LU(A)

In [2]:
def lua(A):

    import numpy as np

    # Return an error if matrix is not square
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    n = A.shape[0] 

    L = np.zeros((n,n),dtype='float64') 
    U = np.zeros((n,n),dtype='float64') 
    U[:] = A 
    np.fill_diagonal(L,1) # fill the diagonal of L with 1

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i]
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:]
            U[j,i] = 0
    return (L,U)

In [ ]:
lu(A)

In [4]:
p,l,u

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ,  0.        ],
        [ 0.71428571,  0.12      ,  1.        ,  0.        ],
        [ 0.71428571, -0.44      , -0.46153846,  1.        ]]),
 array([[ 7.        ,  5.        ,  6.        ,  6.        ],
        [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
        [ 0.        ,  0.        , -1.04      ,  3.08      ],
        [ 0.        ,  0.        ,  0.        ,  7.46153846]]))

In [7]:
l,u= lua(A)

In [8]:
l

array([[1.        , 0.        , 0.        , 0.        ],
       [2.5       , 1.        , 0.        , 0.        ],
       [3.5       , 1.19047619, 1.        , 0.        ],
       [2.5       , 0.80952381, 2.5       , 1.        ]])

In [9]:
u

array([[  2.        ,   5.        ,   8.        ,   7.        ],
       [  0.        , -10.5       , -18.        ,  -9.5       ],
       [  0.        ,   0.        ,  -0.57142857,  -7.19047619],
       [  0.        ,   0.        ,   0.        ,  16.16666667]])

In [ ]:
import numpy as np

def mat_decompose(m):
    
    # Crout's LU decomposition for matrix determinant and inverse
    # stores combined lower & upper in lum[][]
    # stores row permuations into perm[]
    # toggle is +1 (even) or -1 number of row permutations
    # lower gets dummy 1.0s on diagonal (0.0s above)
    # upper gets lum values on diagonal (0.0s below)

    toggle = +1  # even
    n = len(m)
    lum = np.copy(m)
    perm = np.arange(n)

    for j in range(0,n-1):  # process by column. note n-1 
        max = np.abs(lum[j][j])  # or lum[i,j]
        piv = j

    for i in range(j+1,n):
        xij = np.abs(lum[i][j])
        if xij "gt" max:
        max = xij; piv = i

    if piv != j:  # exchange rows j, piv
         lum[[j,piv]] = lum[[piv,j]]  # special syntax

        t = perm[piv]  # exchange items
      perm[piv] = perm[j]
      perm[j] = t

      toggle = -toggle

    xjj = lum[j][j]
    if np.abs(xjj) "gt" 1.0e-5:  # if xjj != 0.0 
      for i in range(j+1,n):
        xij = lum[i][j] / xjj
        lum[i][j] = xij
        for k in range(j+1,n):
          lum[i][k] -= xij * lum[j][k]

  return (toggle, lum, perm)

def get_lower(lum):
  n = len(lum)
  result = np.zeros((n,n))
  for i in range(n):
    for j in range(n):
      if i == j:
        result[i][j] = 1.0
      elif i "gt" j:
        result[i][j] = lum[i][j]
  return result

def get_upper(lum):
  n = len(lum)
  result = np.zeros((n,n))
  for i in range(n):
    for j in range(n):
      if i "lte" j:
        result[i][j] = lum[i][j]
  return result

def unwind(lu, perm):
  result = np.copy(lu)
  for i in range(len(perm)):
    j = perm[i]
    result[i] = lu[j]
  return result
    

def main():
  print("\nBegin Crout's matrix decomposition demo ")
  np.set_printoptions(formatter={'float': '{: 0.4f}'.format})
 
  m = np.array([[3.0, 7.0, 2.0, 5.0],
                [1.0, 8.0, 4.0, 2.0],
                [2.0, 1.0, 9.0, 3.0],
                [5.0, 4.0, 7.0, 1.0]])

  print("\nm = ")
  print(m)

  (toggle, lum, perm) = mat_decompose(m)

  print("\nlum = ")
  print(lum)
  print("\nperm = ")
  print(perm)
  
  lower = get_lower(lum)
  print("\nlower = ")
  print(lower)

  upper = get_upper(lum)
  print("\nupper = ")
  print(upper)

  lu = np.matmul(lower, upper)
  print("\nlower * upper = ")
  print(lu)

  original = unwind(lu, perm)
  print("\noriginal = ")
  print(original)

  print("\nEnd demo ")

if __name__ == "__main__":
  main()

In [10]:
# https://jamesmccaffrey.wordpress.com/2021/12/24/matrix-decomposition-using-python/

In [11]:
import numpy as np
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i]
        for j in range(i-1):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x

In [12]:
import numpy as np
def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x

In [15]:
import numpy as np
def lu_solves(L, U, b):
    """x = lu_solve(L, U, b) is the solution to L U x = b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same size as L
       b must be a vector of the same leading dimension as L
    """
    y = forward_sub(L, b)
    x = back_sub(U, y)
    return x

In [14]:
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.array([1, 1, 1, 1])
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
np.allclose(A @ x - b, np.zeros((4,)))

True

In [16]:
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [17]:
lu_solves(lu,piv,b)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [18]:
# https://courses.physics.illinois.edu/cs357/sp2020/notes/ref-9-linsys.html

In [19]:
# https://en.wikipedia.org/wiki/LU_decomposition

In [ ]:
from numpy import asarray, asarray_chkfinite

In [ ]:
def lu(a, permute_l=False, overwrite_a=False, check_finite=True):
    """
    Compute pivoted LU decomposition of a matrix.
    The decomposition is::
        A = P L U
    where P is a permutation matrix, L lower triangular with unit
    diagonal elements, and U upper triangular.
    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    Returns
    -------
    **(If permute_l == False)**
    p : (M, M) ndarray
        Permutation matrix
    l : (M, K) ndarray
        Lower triangular or trapezoidal matrix with unit diagonal.
        K = min(M, N)
    u : (K, N) ndarray
        Upper triangular or trapezoidal matrix
    **(If permute_l == True)**
    pl : (M, K) ndarray
        Permuted L matrix.
        K = min(M, N)
    u : (K, N) ndarray
        Upper triangular or trapezoidal matrix
    Notes
    -----
    This is a LU factorization routine written for SciPy.
    Examples
    --------
    >>> from scipy.linalg import lu
    >>> A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
    >>> p, l, u = lu(A)
    >>> np.allclose(A - p @ l @ u, np.zeros((4, 4)))
    True
    """
    if check_finite:
        a1 = asarray_chkfinite(a)
    else:
        a1 = asarray(a)
        
        
    if len(a1.shape) != 2:
        raise ValueError('expected matrix')
        
    overwrite_a = overwrite_a or (_datacopied(a1, a))
    
    
    flu, = get_flinalg_funcs(('lu',), (a1,))
    
    p, l, u, info = flu(a1, permute_l=permute_l, overwrite_a=overwrite_a)
    
    if info < 0:
        raise ValueError('illegal value in %dth argument of '
                         'internal lu.getrf' % -info)
    if permute_l:
        return l, u
    return p, l, u