### Exponential integral E1.

In [1]:
import scipy.special as sc

In [2]:
sc.exp1(0)

inf

In [3]:
sc.exp1(-1)

nan

In [4]:
sc.exp1(complex(-1, 0))

(-1.8951178163559368-3.141592653589793j)

In [5]:
sc.exp1(complex(-1, -0.0))

(-1.8951178163559368+3.141592653589793j)

In [6]:
sc.exp1([1, 10, 100, 1000])

array([2.19383934e-01, 4.15696893e-06, 3.68359776e-46, 0.00000000e+00])

In [9]:
import numpy as np 

In [10]:
x = np.array([1, 2, 3, 4])
sc.exp1(x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])

In [11]:
-sc.expi(-x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])

In [6]:
from scipy.integrate import quad

In [7]:
def Ei_2(x, minfloat=1e-7, maxfloat=10000):
    """Ei integral function."""
    minfloat = min(np.abs(x), minfloat)
    maxfloat = max(np.abs(x), maxfloat)
    def f(t):
        return np.exp(-t) / t
    if x > 0:
        return -1.0 * (quad(f, -x, -minfloat)[0] + quad(f, minfloat, maxfloat)[0])
    else:
        return -1.0 * quad(f, -x, maxfloat)[0]

In [5]:
Ei_2(1)

NameError: name 'np' is not defined