# Random sampling

### Simple random data


**`rand`(d0, d1, ..., dn)	Random values in a given shape.**

**`randn`(d0, d1, ..., dn)	Return a sample (or samples) from the “standard normal” distribution.**

**`randint`(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).**

**`random_integers`(low[, high, size])	Random integers of type np.int between low and high, inclusive.**

**`random_sample`([size])	Return random floats in the half-open interval [0.0, 1.0).**

**`random` ([size])	Return random floats in the half-open interval [0.0, 1.0).**

**`ranf` ([size])	Return random floats in the half-open interval [0.0, 1.0).**


**`sample` ([size])	Return random floats in the half-open interval [0.0, 1.0).**

**`choice`(a[, size, replace, p])	Generates a random sample from a given 1-D array**

**`bytes`(length)	Return random bytes.**

# https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

https://github.com/python/cpython/blob/main/Lib/random.py

In [1]:
import numpy as np

In [8]:
np.random.rand(3,4)

array([[0.62425728, 0.46060449, 0.53186621, 0.274369  ],
       [0.58280466, 0.49269813, 0.58104088, 0.3154825 ],
       [0.45536802, 0.28356991, 0.71749316, 0.65718874]])

In [10]:
np.random.randn(3,4)

array([[-0.21366133,  0.40092218,  0.4111987 ,  0.49973803],
       [ 0.14211902,  0.58156513, -0.09406859, -0.59138823],
       [ 0.78069845, -0.47167278,  1.70239639,  0.54464974]])

In [29]:
np.random.randint(3,10)

8

In [16]:
np.random.random_integers(3,10)

C:\Users\md slauddin\AppData\Local\Temp\ipykernel_20044\1753085756.py:1: DeprecationWarning: This function is deprecated. Please call randint(3, 10 + 1) instead
  np.random.random_integers(3,10)


8

In [30]:
np.random.random_sample(4)

array([0.56029555, 0.67842967, 0.54730938, 0.68540442])

In [32]:
np.random.random()

0.4381525927543639

In [33]:
np.random.ranf(3)

array([0.8728921 , 0.42934679, 0.40767094])

In [34]:
np.random.sample(3)

array([0.27429421, 0.28172373, 0.55254783])

In [40]:
np.random.choice([1,2,3,4],(2,2))

array([[1, 4],
       [2, 1]])

In [41]:
np.random.bytes(2)

b'\xf8]'

https://pythonsansar.com/random-module-in-python/#:~:text=Random%20Module%20in%20Python%201%20Introduction%20The%20random,value%20from%20a%20sequence%2C%20and%20so%20on.%20

file:///C:/Users/md%20slauddin/AppData/Local/Microsoft/Windows/INetCache/IE/BCKERTVE/What%20Are%20Random%20Numbers%20and%20How%20Are%20They%20Used_[1].mhtml

https://www.quora.com/Are-there-any-algorithms-that-use-a-random-number-generator

https://en.wikipedia.org/wiki/List_of_random_number_generators

In [42]:
import numpy as np

In [43]:
def normal_dist(x , mean , sd):
    prob_density = (np.pi*sd) * np.exp(-0.5*((x-mean)/sd)**2)
    return prob_density
 

In [47]:
normal_dist(2,2,2)

6.283185307179586