In [1]:
import scipy.special as sp

In [2]:
sp.riccati_jn(2,3)

(array([0.14112001, 1.0370325 , 0.89591249]),
 array([-0.9899925 , -0.20455749,  0.43975751]))

In [3]:
sp.spherical_jn(3,2)*3

0.18216629298862463

In [4]:
sp.spherical_jn(1,0)*1

0.0

In [5]:
sp.spherical_jn(1,1)*1

0.3011686789397571

In [6]:
sp.spherical_jn(2,2)*2

0.3968958981142935

In [7]:
sp.spherical_jn(2,3)*3

0.8959124912272007

In [8]:
sp.jn(2,3)

0.4860912605858912

In [9]:
sp.j0(3)

-0.2600519549019335

In [10]:
sp.jn(0,1)

0.7651976865579666

In [11]:
from math import pi
import scipy.special as sp 
def riccati_jn(n,x):
    return (x*sp.spherical_jn(n,x))

In [12]:
riccati_jn(2,3)

0.8959124912272007

In [13]:
sp.riccati_jn(2,3)

(array([0.14112001, 1.0370325 , 0.89591249]),
 array([-0.9899925 , -0.20455749,  0.43975751]))

In [ ]:
sp.riccati_jn(4,5)

In [ ]:
riccati_jn(0,5),riccati_jn(1,5),riccati_jn(2,5),riccati_jn(3,5),riccati_jn(4,5)

In [14]:
from math import pi
import scipy.special as sp 
from scipy.special import spherical_jn
import numpy as np 
def riccati_jn(n,x):
    for rng in range(0,n+1):
        c = (x*sp.spherical_jn(rng,x))
        print(c)
        


In [16]:
riccati_jn(2,3)

0.1411200080598672
1.0370324992870679
0.8959124912272007


In [15]:
riccati_jn(4,5)

-0.9589242746631386
-0.47544704039585395
0.6736560504256262
1.14910309082148
0.9350882767244459
