In [55]:
import matrices as mat

In [58]:
import numpy as np

In [60]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
mat.add(A,B)

TypeError: object of type 'numpy.int32' has no len()

In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([[3,4,5],[5,6,7]])

In [3]:
np.add(ar1,ar2)

array([[ 4,  6,  8],
       [ 9, 11, 13]])

In [61]:
import numpy as np
def add(A, B):
    """
    Adds two matrices and returns the sum
        :param A: The first matrix
        :param B: The second matrix
 
        :return: Matrix sum
    """
    # Section 1: Ensure dimensions are valid for matrix addition
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    if rowsA != rowsB or colsA != colsB:
        raise ArithmeticError('Matrices are NOT the same size.')
 
    # Section 2: Create a new matrix for the matrix sum
    C = zeros(rowsA, colsB)
 
    # Section 3: Perform element by element sum
    for i in range(rowsA):
        for j in range(colsB):
            C[i][j] = A[i][j] + B[i][j]
 
    return np.array(C)

In [62]:
add(ar1,ar2)

array([[ 4.,  6.,  8.],
       [ 9., 11., 13.]])

TypeError: add() missing 1 required positional argument: 'B'

In [17]:
def zeros(rows, cols):
    """
    Creates a matrix filled with zeros.
        :param rows: the number of rows the matrix should have
        :param cols: the number of columns the matrix should have
 
        :return: list of lists that form the matrix
    """
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(0.0)
 
    return np.array(M)

In [18]:
zeros(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
shape = (3,4)

In [20]:
 = shape[0]

3

In [26]:
def subtract(A, B):
    """
    Subtracts matrix B from matrix A and returns difference
        :param A: The first matrix
        :param B: The second matrix
 
        :return: Matrix difference
    """
    # Section 1: Ensure dimensions are valid for matrix subtraction
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    if rowsA != rowsB or colsA != colsB:
        raise ArithmeticError('Matrices are NOT the same size.')
 
    # Section 2: Create a new matrix for the matrix difference
    C = zeros_matrix(rowsA, colsB)
 
    # Section 3: Perform element by element subtraction
    for i in range(rowsA):
        for j in range(colsB):
            C[i][j] = A[i][j] - B[i][j]
 
    return np.array(C)

In [27]:
subtract(ar1,ar2)

array([[-2, -2, -2],
       [-1, -1, -1]])

In [21]:
np.subtract(ar1,ar2)

array([[-2, -2, -2],
       [-1, -1, -1]])

In [32]:
def multiply(A, B):
    """
    Returns the product of the matrix A * B
        :param A: The first matrix - ORDER MATTERS!
        :param B: The second matrix
 
        :return: The product of the two matrices
    """
    # Section 1: Ensure A & B dimensions are correct for multiplication
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    if colsA != rowsB:
        raise ArithmeticError(
            'Number of A columns must equal number of B rows.')
 
    # Section 2: Store matrix multiplication in a new matrix
    C = zeros(rowsA, colsB)
    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total
 
    return C

In [31]:
ar1, ar2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[3, 4, 5],
        [5, 6, 7]]))

In [28]:
np.multiply(ar1,ar2)

array([[ 3,  8, 15],
       [20, 30, 42]])

In [30]:
multiply(ar1,ar2)

ArithmeticError: Number of A columns must equal number of B rows.

In [ ]:
def copy(M):
    """
    Creates and returns a copy of a matrix.
        :param M: The matrix to be copied
 
        :return: A copy of the given matrix
    """
    # Section 1: Get matrix dimensions
    rows = len(M)
    cols = len(M[0])
 
    # Section 2: Create a new matrix of zeros
    MC = zeros(rows, cols)
 
    # Section 3: Copy values of M into the copy
    for i in range(rows):
        for j in range(cols):
            MC[i][j] = M[i][j]
 
    return np.array(MC)

In [ ]:
def diag(ctx, diagonal, **kwargs):
        """
        Create square diagonal matrix using given list.

        Example:
        >>> from mpmath import diag, mp
        >>> mp.pretty = False
        >>> diag([1, 2, 3])
        matrix(
        [['1.0', '0.0', '0.0'],
         ['0.0', '2.0', '0.0'],
         ['0.0', '0.0', '3.0']])
        """
        A = ctx.matrix(len(diagonal), **kwargs)
        for i in xrange(len(diagonal)):
            A[i,i] = diagonal[i]
        return A

In [ ]:
import numpy as np 
def identity(n):
    """
    Creates and returns an identity matrix.
        :param n: the square size of the matrix
 
        :return: a square identity matrix
    """
    IdM = zeros(n, n)
    for i in range(n):
        IdM[i][i] = 1.0
 
    return np.array(IdM)

In [33]:
def transpose(matrix):
    listOfLists = []
    for row in range(len(matrix[0])):
        colList = []
        for col in range(len(matrix)):
            colList.append(matrix[col][row])
    listOfLists.append(colList)

    return np.array(listOfLists)

In [34]:
np.transpose(ar1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
transpose(ar1)

array([[3, 6]])

In [38]:
def transpose(m):
    return np.array((list(map(list,list(zip(*m))))))

In [39]:
transpose(ar1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
def divide_matrix(A):
    mid = len(A)//2
    m_11 = [M[:mid] for M in A[:mid]]
    m_12 = [M[mid:] for M in A[:mid]]
    m_21 = [M[:mid] for M in A[mid:]]
    m_22 = [M[mid:] for M in A[mid:]]

    return (m_11, m_12, m_21, m_22)

In [41]:
np.divide(ar1,ar2)

array([[0.33333333, 0.5       , 0.6       ],
       [0.8       , 0.83333333, 0.85714286]])

In [43]:
divide_matrix(ar1)

([array([1])], [array([2, 3])], [array([4])], [array([5, 6])])

In [44]:
def scalar_mult(num, mat) :
    new_mat = []
    for i in mat :
        part = []
        for j in i :
            part.append(num*j)
        new_mat.append(part)
    return new_mat

In [45]:

scalar_mult(2,ar1)

[[2, 4, 6], [8, 10, 12]]

In [47]:
ar1*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
ar1,ar2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[3, 4, 5],
        [5, 6, 7]]))

In [50]:
ar1 @ ar2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [51]:
# https://www.geeksforgeeks.org/matrix-manipulation-python/

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
def ones(shape):
    ones = []
    row = shape[0]
    col = shape[1]
    for i in row:
        row=ones.append(1)
        for j in col:
            col= ones.append(1)
            
    return row,col
        

In [54]:
ones((2,3))

TypeError: 'int' object is not iterable