In [1]:
from scipy import special
a, ap, ai, aip = special.ai_zeros(3)
a

array([-2.33810741, -4.08794944, -5.52055983])

In [2]:
ap

array([-1.01879297, -3.24819758, -4.82009921])

In [3]:
ai

array([ 0.53565666, -0.41901548,  0.38040647])

In [4]:
aip

array([ 0.70121082, -0.80311137,  0.86520403])

In [5]:
import scipy.special as sp 

In [6]:
sp.airy(3)

(0.006591139357460717,
 -0.011912976705951313,
 14.037328963730229,
 22.92221496638217)