In [1]:
from scipy import special
b, bp, bi, bip = special.bi_zeros(3)
b

array([-1.17371322, -3.2710933 , -4.83073784])

In [2]:
bp

array([-2.29443968, -4.07315509, -5.51239573])

In [3]:
bi

array([-0.45494438,  0.39652284, -0.36796916])

In [4]:
bip

array([ 0.60195789, -0.76031014,  0.83699101])