In [1]:
import scipy.special as sc

In [2]:
sc.gammasgn([1, 2, 3, 4])

array([1., 1., 1., 1.])

In [3]:
sc.gammasgn([-0.5, -1.5, -2.5, -3.5])

array([-1.,  1., -1.,  1.])

In [4]:
import numpy as np 

In [5]:
x = [1.5, 0.5, -0.5, -1.5]
sc.gammasgn(x) * np.exp(sc.gammaln(x))

array([ 0.88622693,  1.77245385, -3.5449077 ,  2.3632718 ])

In [6]:
sc.gamma(x)

array([ 0.88622693,  1.77245385, -3.5449077 ,  2.3632718 ])

In [7]:
sc.gammasgn(x)

array([ 1.,  1., -1.,  1.])

In [8]:
def gammasgn(x):
    if x >= 0:
        return 1.0
    else:
        return -1

In [10]:
gammasgn(5)

1.0