In [1]:
import numpy as np 

In [2]:
A = np.array([[1.0,4.0,1.0], [1.0,6.0,-1.0], [2.0,-1.0,2.0]])
b = np.array([7.0,13.0,5.0])


In [3]:
A

array([[ 1.,  4.,  1.],
       [ 1.,  6., -1.],
       [ 2., -1.,  2.]])

In [4]:
def LUdecomp(a):
    n = len(A)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] !=0.0:
                lam = a[i,k]/ a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam 
    return a 

In [5]:
LUdecomp(A)

array([[ 1. ,  4. ,  1. ],
       [ 1. ,  2. , -2. ],
       [ 2. , -4.5, -9. ]])

In [6]:
LUdecomp(A)

array([[ 1.  ,  4.  ,  1.  ],
       [ 1.  , -2.  , -3.  ],
       [ 2.  ,  6.25,  7.75]])

In [7]:
LUdecomp(A)

array([[ 1.        ,  4.        ,  1.        ],
       [ 1.        , -6.        , -4.        ],
       [ 2.        ,  0.29166667,  6.91666667]])

In [8]:
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k], b[0:k])
    b[n-1]  = b[n-1] /a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n], b[k+1:n])) /a[k,k]
    return b 
    
    

In [9]:
Ap = LUdecomp(A)
Ap

array([[  1.        ,   4.        ,   1.        ],
       [  1.        , -10.        ,  -5.        ],
       [  2.        ,   0.77083333,   8.77083333]])

In [10]:
LUsolve(Ap,b)

array([ 7.84655582,  0.17672209, -1.55344418])