### Compute the 2-D discrete Fourier Transform

In [15]:
import numpy as np
import scipy.fft
x = np.mgrid[:5, :5][0]
scipy.fft.fft2(x)

array([[ 50.  -0.j        ,   0.  +0.j        ,   0.  +0.j        ,
          0.  -0.j        ,   0.  -0.j        ],
       [-12.5+17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  -0.j        ,   0.  -0.j        ],
       [-12.5 +4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  -0.j        ,   0.  -0.j        ],
       [-12.5 -4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  -0.j        ,   0.  -0.j        ],
       [-12.5-17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  -0.j        ,   0.  -0.j        ]])

In [16]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [17]:
import cmath
import numpy as np
from math import log, ceil
def pad2(x):
    m, n = np.shape(x)
    M, N = 2 ** int(ceil(log(m, 2))), 2 ** int(ceil(log(n, 2)))
    F = np.zeros((M,N), dtype = x.dtype)
    F[0:m, 0:n] = x
    return F, m, n

def fft2(f):
    '''FFT of 2-d signals/images with padding
    usage X, m, n = fft2(x), where m and n are dimensions of original signal'''

    f, m, n = pad2(f)
    return np.transpose(scipy.fft.fft(np.transpose(scipy.fft.fft(f))))


In [18]:
fft2(x)

array([[ 50.         -0.j        ,   0.        -24.14213562j,
         10.         -0.j        ,   0.         -4.14213562j,
         10.         -0.j        ,   0.         +4.14213562j,
         10.         +0.j        ,   0.        +24.14213562j],
       [-27.07106781-24.14213562j, -11.65685425+13.07106781j,
         -5.41421356 -4.82842712j,  -2.         +2.24264069j,
         -5.41421356 -4.82842712j,   2.         -2.24264069j,
         -5.41421356 -4.82842712j,  11.65685425-13.07106781j],
       [ 10.        +10.j        ,   4.82842712 -4.82842712j,
          2.         +2.j        ,   0.82842712 -0.82842712j,
          2.         +2.j        ,  -0.82842712 +0.82842712j,
          2.         +2.j        ,  -4.82842712 +4.82842712j],
       [-12.92893219 -4.14213562j,  -2.         +6.24264069j,
         -2.58578644 -0.82842712j,  -0.34314575 +1.07106781j,
         -2.58578644 -0.82842712j,   0.34314575 -1.07106781j,
         -2.58578644 -0.82842712j,   2.         -6.24264069j],
    

In [19]:
scipy.fft.fft2([[5,6]])

array([[11.-0.j, -1.-0.j]])

In [20]:
x = np.array([[5,6]])
fft2(x)

array([[11.-0.j, -1.-0.j]])