In [1]:
def zeros_matrix(rows, cols):
    """
    Creates a matrix filled with zeros.
        :param rows: the number of rows the matrix should have
        :param cols: the number of columns the matrix should have
 
        :return: list of lists that form the matrix
    """
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(0.0)
 
    return M

In [2]:
def matrix_multiply(A, B):
    """
    Returns the product of the matrix A * B
        :param A: The first matrix - ORDER MATTERS!
        :param B: The second matrix
 
        :return: The product of the two matrices
    """
    # Section 1: Ensure A & B dimensions are correct for multiplication
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    if colsA != rowsB:
        raise ArithmeticError(
            'Number of A columns must equal number of B rows.')
 
    # Section 2: Store matrix multiplication in a new matrix
    C = zeros_matrix(rowsA, colsB)
    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total
 
    return C

In [3]:
def multiply_matrices(list):
    """
    Find the product of a list of matrices from first to last
        :param list: The list of matrices IN ORDER
 
        :return: The product of the matrices
    """
    # Section 1: Start matrix product using 1st matrix in list
    matrix_product = list[0]
 
    # Section 2: Loop thru list to create product
    for matrix in list[1:]:
        matrix_product = matrix_multiply(matrix_product, matrix)
 
    return matrix_product

In [4]:
import numpy as np 
A = np.array([[2,1,0],[1,1,1],[-1,4,3]])
B = np.array([[1,1],[0,1],[-1,3]])
A,B

(array([[ 2,  1,  0],
        [ 1,  1,  1],
        [-1,  4,  3]]),
 array([[ 1,  1],
        [ 0,  1],
        [-1,  3]]))

In [5]:
np.matmul(A,B)

array([[ 2,  3],
       [ 0,  5],
       [-4, 12]])

In [6]:
matrix_multiply(A,B)

[[2, 3], [0, 5], [-4, 12]]