In [1]:
import numpy as np 

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.T

In [ ]:
arr.transpose()

**Matrix A , we define its transpose**

**A^T , by swapping rows with cols**

In [ ]:
# Python3 Program to find
# transpose of a matrix

N = 4

# Finds transpose of A[][] in-place
def transpose(A):

for i in range(N):
for j in range(i+1, N):
A[i][j], A[j][i] = A[j][i], A[i][j]

# driver code
A = [ [1, 1, 1, 1],
[2, 2, 2, 2],
[3, 3, 3, 3],
[4, 4, 4, 4]]

transpose(A)

print("Modified matrix is")
for i in range(N):
for j in range(N):
print(A[i][j], " ", end='')
print()

# This code is contributed by Anant Agarwal.


In [ ]:
# Python3 Program to find
# transpose of a matrix

N = 4

# This function stores
# transpose of A[][] in B[][]

def transpose(A,B):

for i in range(N):
for j in range(N):
B[i][j] = A[j][i]

# driver code
A = [ [1, 1, 1, 1],
[2, 2, 2, 2],
[3, 3, 3, 3],
[4, 4, 4, 4]]


B = A[:][:] # To store result

transpose(A, B)

print("Result matrix is")
for i in range(N):
for j in range(N):
print(B[i][j], " ", end='')
print()

# This code is contributed by Anant Agarwal.


In [ ]:
arr


'I am new on Python i am working on Transpose of matrix but i found it lengthy code any short procedure please!'

In [ ]:
def transpose(*args):
    for myrow in args: 
        print(myrow) 
        print("\n") 
        t_matrix = zip(*args) 
    for myrow in t_matrix: 
        print(myrow)

In [ ]:
transpose(arr)

In [ ]:
mymatrix=[(1,2,3),(4,5,6),(7,8,9),(10,11,12)] 
myTransposedMatrix = list(zip(*arr))
myTransposedMatrix

In [ ]:
# given matrix A
A = [[2, 3, 1],
     [1, 2, 3]]
rows = len(A)
columns = len(A[0])
# Initialize the transpose of matrices elements to 0
# with rows as columns and columns as rows as dimensions
matrixTrans = [[0, 0],
               [0, 0],
               [0, 0]]
# iterate through rows
for i in range(rows):
    # iterate through columns
    for j in range(columns):
        matrixTrans[j][i] = A[i][j]
# printing the transpose of matrices
print("Printing the transpose of matrices : ")
for rows in matrixTrans:
    print(*rows)

In [ ]:
zip(*arr)

In [ ]:
arr

In [ ]:
np.array([list(x) for x in zip(*arr)])

In [ ]:
map(list, zip(*arr))

In [ ]:
def matrixTranspose(anArray):
    transposed = [None]*len(anArray[0])
    for t in range(len(anArray)):
        for tt in range(len(anArray[t])):
            transposed[t] = [None]*len(anArray)
            transposed[t][tt] = anArray[tt][t]
    print (transposed)

In [ ]:
matrixTranspose(arr)

In [ ]:
theArray = [['a','b','c'],['d','e','f'],['g','h','i']]
zip(*theArray)

In [ ]:
np.array( [*zip(*theArray)])

In [ ]:
theArray.T

In [ ]:
#https://stackoverflow.com/questions/4937491/matrix-transpose-in-python

In [3]:
def matrixTranspose( matrix ):
    if not matrix: return []
    return [ [ row[ i ] for row in matrix ] for i in range( len( matrix[ 0 ] ) ) ]

In [4]:
matrixTranspose(arr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [5]:
import itertools
def transpose(list_of_lists):
    return list(itertools.izip_longest(*list_of_lists,fillvalue=' '))

In [6]:
transpose(arr)

AttributeError: module 'itertools' has no attribute 'izip_longest'

In [7]:
def transpose(matrix):
    x=0
    trans=[]
    b=len(matrix[0])
    while b!=0:
        trans.append([])
        b-=1
    for list in matrix:
        for element in list:
            trans[x].append(element)
            x+=1
        x=0
    return trans

In [9]:
np.array(transpose(arr))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
def transpose(matrix):
    listOfLists = []
    for row in range(len(matrix[0])):
        colList = []
        for col in range(len(matrix)):
            colList.append(matrix[col][row])
    listOfLists.append(colList)

    return listOfLists

In [11]:
transpose(arr)

[[3, 6, 9]]

In [12]:
def transpose(m):
    return(list(map(list,list(zip(*m)))))

In [13]:
transpose(arr)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [15]:
# https://stackoverflow.com/questions/4937491/matrix-transpose-in-python

# List to array convert

In [16]:
import numpy as np

def rotate_clockwise(x):
    return x[::-1].T


def find(element, matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == element:
                return (i+1, j+1)
N = int(input())
S = int(input())

arr = np.array(range(0,N*N))

arr.shape = N,N
for i in range(S):
    a,b,c = [int(x) for x in input().split()]
    arr[a - 1:a + c, b - 1:b + c] = rotate_clockwise(arr[a - 1:a + c, b - 1:b + c])


M = int(input())
items = np.array(range(0,M))
for i in range(M):
    danscisayisi=int(input())
    items[i]=(danscisayisi)

for i in range(0, len(items)):
    items[i] = int(items[i])
noktalar = np.array(range(0,M))
for i in range(M):
    coord=(find(items[i],arr))
    result = " ".join(str(x) for x in coord)
    print(result)

2
1
2


ValueError: not enough values to unpack (expected 3, got 1)

In [21]:
arr

array([[0, 1],
       [2, 3]])

In [20]:
arr_conv= transpose(arr)
arr_conv

[[0, 2], [1, 3]]

In [19]:
def print_array(a):
    """ Take a nested list a and print it like a NumPy array. """
    for i, row in enumerate(a):
        if i == 0:
            first_char = '['
        else: 
            first_char = ' '
        if i == len(a) - 1:
            last_char = ']'
        else: 
            last_char = ''    
        print(first_char + '[' + 
              ' '.join(str(i) for i in row) + ']' + last_char)
        
print_array(arr_conv)

[[0 2]
 [1 3]]


In [23]:
zeros_matrix(3,4)

[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]

In [27]:
def print_matrix(M, decimals=3):
    """
    Print a matrix one row at a time
        :param M: The matrix to be printed
    """
    for row in M:
        print([round(x,decimals)+0 for x in row])

In [28]:
def transpose(M):
    """
    Returns a transpose of a matrix.
        :param M: The matrix to be transposed
 
        :return: The transpose of the given matrix
    """
    # Section 1: if a 1D array, convert to a 2D array = matrix
    if not isinstance(M[0],list):
        M = [M]
 
    # Section 2: Get dimensions
    rows = len(M)
    cols = len(M[0])
 
    # Section 3: MT is zeros matrix with transposed dimensions
    MT = zeros_matrix(cols, rows)
 
    # Section 4: Copy values from M to it's transpose MT
    for i in range(rows):
        for j in range(cols):
            MT[j][i] = M[i][j]
 
    return MT

In [32]:
def check_matrix_equality(A, B, tol=None):
    """
    Checks the equality of two matrices.
        :param A: The first matrix
        :param B: The second matrix
        :param tol: The decimal place tolerance of the check
 
        :return: The boolean result of the equality check
    """
    # Section 1: First ensure matrices have same dimensions
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return False
 
    # Section 2: Check element by element equality
    #            use tolerance if given
    for i in range(len(A)):
        for j in range(len(A[0])):
            if tol == None:
                if A[i][j] != B[i][j]:
                    return False
            else:
                if round(A[i][j],tol) != round(B[i][j],tol):
                    return False
 
    return True

In [33]:
def unitize_vector(vector):
    """
    Find the unit vector for a vector
        :param vector: The vector to find a unit vector for
 
        :return: A unit-vector of vector
    """
    # Section 1: Ensure that a vector was given
    if len(vector) > 1 and len(vector[0]) > 1:
        raise ArithmeticError(
            'Vector must be a row or column vector.')
 
    # Section 2: Determine vector magnitude
    rows = len(vector); cols = len(vector[0])
    mag = 0
    for row in vector:
        for value in row:
            mag += value ** 2
    mag = mag ** 0.5
 
    # Section 3: Make a copy of vector
    new = copy_matrix(vector)
 
    # Section 4: Unitize the copied vector
    for i in range(rows):
        for j in range(cols):
            new[i][j] = new[i][j] / mag
 
    return new

In [34]:
# https://integratedmlai.com/basic-linear-algebra-tools-in-pure-python-without-numpy-or-scipy/

In [36]:
m = ([1, 2, 3], [7, 1, 5], [0, 9, 3])
for i in m:
     print("". join(str(i)))

[1, 2, 3]
[7, 1, 5]
[0, 9, 3]
