Operation on Matrix : 

1. add() :- This function is used to perform element wise matrix addition. 
2. subtract() :- This function is used to perform element wise matrix subtraction. 
3. divide() :- This function is used to perform element wise matrix division. 

In [1]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [5]:
import numpy as np
np.add(4,5)

9

In [21]:
def add_matrix(X, Y):
    
    n = len(X)
    if n == 1:
        
        return [[X[0][0] + Y[0][0]]]
    S = []
    
    for i in range(n):
        S.append([])
        for j in range(n):
            S[i].append(X[i][j] + Y[i][j])
    return S

In [23]:
add_matrix(x,y)

[[8, 10], [13, 15]]

In [25]:
def sub_matrix(X, Y):
    
    n = len(X)
    if n == 1:
        return [[X[0][0] - Y[0][0]]]
    S = []
    for i in range(n):
        S.append([])
        for j in range(n):
           
            S[i].append(X[i][j] - Y[i][j])
    return S

In [26]:
sub_matrix(x,y)

[[-6, -6], [-5, -5]]

In [27]:
def mul_matrix(X, Y):
    
    Z = [[0 for i in range(len(X))] for j in range(len(Y))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(X[0])):
                Z[i][j] += X[i][k] * Y[k][j]
    return Z

In [28]:
mul_matrix(x,y)

[[25, 28], [73, 82]]

In [29]:
def divide_matrix(A):
    mid = len(A)//2
    m_11 = [M[:mid] for M in A[:mid]]
    m_12 = [M[mid:] for M in A[:mid]]
    m_21 = [M[:mid] for M in A[mid:]]
    m_22 = [M[mid:] for M in A[mid:]]

    return (m_11, m_12, m_21, m_22)

In [30]:
def merge_matrix(matrix_11, matrix_12, matrix_21, matrix_22):
    matrix_total = []
    rows1 = len(matrix_11)
    rows2 = len(matrix_21)
    for i in range(rows1):
        matrix_total.append(matrix_11[i] + matrix_12[i])
    for j in range(rows2):
        matrix_total.append(matrix_21[j] + matrix_22[j])
    return matrix_tota

In [31]:
def strassen(X, Y):
    if len(X) == 1:
        return [[X[0][0] * Y[0][0]]]
    else:
        A, B, C, D = divide_matrix(X)
        E, F, G, H = divide_matrix(Y)
    
        P1 = strassen(A, sub_matrix(F,H))
        P2 = strassen(add_matrix(A, B), H)
        P3 = strassen(add_matrix(C, D), E)
        P4 = strassen(D, sub_matrix(G, E))
        P5 = strassen(add_matrix(A, D), add_matrix(E, H))
        P6 = strassen(sub_matrix(B, D), add_matrix(G, H))
        P7 = strassen(sub_matrix(A, C), add_matrix(E, F))
    
        Z11 = add_matrix(sub_matrix(add_matrix(P5, P4), P2), P6)
        Z12 = add_matrix(P1, P2)
        Z21 = add_matrix(P3, P4)
        Z22 = sub_matrix(sub_matrix(add_matrix(P5, P1), P3), P7)

        return merge_matrix(Z11, Z12, Z21, Z22)

In [33]:
A = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
B = [[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,0]]

print("Strassen")
print(*strassen(A,B), sep='\n')
print("\nClásica")
print(*mul_matrix(A,B), sep='\n')

Strassen


NameError: name 'matrix_tota' is not defined

In [19]:
def add(X,Y):
    
    for i in range(len(X)):
   # iterate through columns
        for j in range(len(X[0])):
        
            result[i][j] = X[i][j] + Y[i][j]

    for r in result:
    
        print(r)

In [20]:
add(x,y)

NameError: name 'result' is not defined

In [ ]:
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
        
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    
    print(r)

4. multiply() :- This function is used to perform element wise matrix multiplication. 
5. dot() :- This function is used to compute the matrix multiplication, rather than element wise multiplication

In [2]:
# Python code to demonstrate matrix operations
# multiply() and dot()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))

# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))


The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]


6. sqrt() :- This function is used to compute the square root of each element of matrix. 
7. sum(x,axis) :- This function is used to add all the elements in matrix. Optional “axis” argument computes the column sum if axis is 0 and row sum if axis is 1. 
8. “T” :- This argument is used to transpose the specified matrix. 
Implementation:

In [3]:
# Python code to demonstrate matrix operations
# sqrt(), sum() and "T"

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using sqrt() to print the square root of matrix
print ("The element wise square root is : ")
print (numpy.sqrt(x))

# using sum() to print summation of all elements of matrix
print ("The summation of all matrix element is : ")
print (numpy.sum(y))

# using sum(axis=0) to print summation of all columns of matrix
print ("The column wise summation of all matrix is : ")
print (numpy.sum(y,axis=0))

# using sum(axis=1) to print summation of all columns of matrix
print ("The row wise summation of all matrix is : ")
print (numpy.sum(y,axis=1))

# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)


The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of all matrix element is : 
34
The column wise summation of all matrix is : 
[16 18]
The row wise summation of all matrix is : 
[15 19]
The transpose of given matrix is : 
[[1 4]
 [2 5]]
