In [1]:
from scipy.linalg import circulant
circulant([1, 2, 3])

array([[1, 3, 2],
       [2, 1, 3],
       [3, 2, 1]])

In [10]:
import numpy as np

def construct_cirlulant(row):

    N =  np.size(row) #row.size
    
    C = np.empty((N, N))

    for i in range(N):

        C[i, i:] = row[:N-i]
        C[i, :i] = row[N-i:]

    return C

In [12]:
construct_cirlulant([1, 2, 3])

array([[1., 2., 3.],
       [3., 1., 2.],
       [2., 3., 1.]])

In [13]:
def construct_P(N):

    P = np.zeros((N, N))

    for i in range(N-1):
        P[i, i+1] = 1
    P[-1, 0] = 1

    return P

In [14]:
construct_P(4)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [16]:
import numpy as np

def find_eigenvalues(n):

  matrix = [[1 if (i+j)%2 == 0 else 0  for j in range(n)] for i in range(n)] 
  A = np.array(matrix)

  eigs = list(map(lambda x: int(x),list(filter(lambda x: x > 10**(-13),list(set(np.linalg.eigvals(A)))))))
  return eigs