In [1]:
import numpy as np

In [ ]:
np.array()

In [33]:
__dtype__ = [ int,
         float
        ]
def array(object,  dtype=None, *, ndmin=0):
    
    return print("array \n",(object))

In [34]:
 a = array([[1,2,3,4],[4,5,6]], dtype=float)

array 
 [[1, 2, 3, 4], [4, 5, 6]]


In [23]:
a

[[1, 2, 3, 4], [4, 5, 6]]

In [24]:
len(a)

2

In [25]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [26]:
np.array([[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
def matrix(object, * , dtype=None, ndim=0):
    
     ==
    return object

In [43]:
matrix([[1,2,3,4],[1,2,3,4]])

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [1]:
# https://www.codeformech.com/types-of-matrices-linear-algebra-using-python/

In [2]:
import numpy as np

In [3]:
np.empty([2, 2])

array([[6.08532842e+247, 1.27734658e-152],
       [3.99911752e+252, 2.34840919e+251]])

In [4]:
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[6553700, 7209065, 4259932],
       [7340144, 6357060, 6357108]])

In [5]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
x = np.arange(6)
x = x.reshape((2, 3))
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [10]:
x = np.arange(6)
x = x.reshape((2, 3))
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [12]:
x = np.arange(6, dtype=int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [30]:
dtype =['int','float']

def sum(a,b,dtype=int):
    c = dtype (a+b) 
    return c

In [31]:
sum(2,3)

5